package ru.stqa.pft.addressbook.tests.contact_test;// Generated by Selenium IDE
import org.junit.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import ru.stqa.pft.addressbook.model.ContactData1;
import ru.stqa.pft.addressbook.tests.TestBase;

public class ContactsCreation extends TestBase {

  @Test
  public void testContactCreation() {
    app.getContactHelper().addNewContact();
    app.getContactHelper().fillContactForm(new ContactData1("oleg", "kozyrev", "igorevich", "tester", "best", "Company1", "89999999", "oleg.k@msp360.com"));
    app.getContactHelper().submitContactCreation();
    app.getContactHelper().goToHomePage();
  }
}

