package ru.stqa.pft.addressbook.tests.contact_test;// Generated by Selenium IDE
import org.junit.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import ru.stqa.pft.addressbook.model.ContactData1;
import ru.stqa.pft.addressbook.tests.TestBase;

public class ContactCreation extends TestBase {

  @Test
  public void testContactCreation() {
    app.getContactHelper().addNewContact();
    app.getContactHelper().fillContactForm(new ContactData1(null, null, "igorevich", "tester", "best", "Company 1", null, "oleg.k@msp360.com", "Test 1"),true);
    app.getContactHelper().submitContactCreation();
    app.getNavigationHelper().goToHomePage();
  }
}

