package ru.stqa.pft.addressbook.tests.group_tests;// Generated by Selenium IDE

import org.junit.Test;
import org.testng.Assert;
import ru.stqa.pft.addressbook.model.GroupData;
import ru.stqa.pft.addressbook.tests.TestBase;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

public class GroupCreationTests extends TestBase {

  @Test
  public void testGroupCreation() {
    app.getNavigationHelper().goToGroupPage();
    int before = app.getGroupHelper().getGroupCount();
    app.getGroupHelper().createGroup(new GroupData("Test 1", "Test 2", null));
    int after = app.getGroupHelper().getGroupCount();
    Assert.assertEquals(after,before + 1);
  }

}
