// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test5contactmodificationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test5contactmodification() {
    driver.get("http://localhost:8080/addressbook/");
    driver.manage().window().setSize(new Dimension(1003, 698));
    driver.findElement(By.cssSelector(".odd:nth-child(3) > .center:nth-child(8) img")).click();
    driver.findElement(By.name("bday")).click();
    {
      WebElement dropdown = driver.findElement(By.name("bday"));
      dropdown.findElement(By.xpath("//option[. = '1']")).click();
    }
    driver.findElement(By.cssSelector("select:nth-child(63) > option:nth-child(3)")).click();
    driver.findElement(By.name("bmonth")).click();
    {
      WebElement dropdown = driver.findElement(By.name("bmonth"));
      dropdown.findElement(By.xpath("//option[. = 'January']")).click();
    }
    driver.findElement(By.cssSelector("select:nth-child(64) > option:nth-child(3)")).click();
    driver.findElement(By.name("byear")).click();
    driver.findElement(By.name("byear")).sendKeys("1999");
    driver.findElement(By.id("15")).click();
    driver.findElement(By.name("searchform")).click();
    driver.findElement(By.id("15")).click();
    driver.findElement(By.id("15")).click();
    driver.findElement(By.name("searchform")).click();
    driver.findElement(By.id("15")).click();
    driver.findElement(By.id("16")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) > .center:nth-child(8) img")).click();
    driver.findElement(By.name("byear")).sendKeys(Keys.ENTER);
  }
}
